'use client';

import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

export type Language = 'en' | 'pa' | 'hi';

type LanguageContextType = {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.map': 'Map',
    'nav.add': 'Add Langar',
    'nav.search': 'Search',
    'nav.gurudwaras': 'Gurudwaras',
    'nav.verified': 'Verified',
    'nav.regularFeeders': 'Regular Feeders',
    'nav.historical': 'Historical',
    'nav.whatsapp': 'WhatsApp Community',
    'nav.dashboard': 'Dashboard',
    'nav.signin': 'Sign In',
    'nav.signout': 'Sign Out',
    'hero.tagline': 'Langar Sab Da, Sewa Sab Lai',
    'hero.subtitle': 'Find free community meals at Gurudwaras and venues near you',
    'hero.searchPlaceholder': 'Search langar near you',
    'hero.detectLocation': 'Use my location',
    'filter.nearby': 'Nearby',
    'filter.today': 'Today',
    'filter.tomorrow': 'Tomorrow',
    'filter.thisWeek': 'This Week',
    'filter.all': 'All',
    'filter.gurudwara': 'Gurudwara',
    'filter.community': 'Community',
    'filter.specialOccasion': 'Special Occasion',
    'filter.freeFood': 'Free Food',
    'filter.verified': 'Only Verified',
    'filter.nearMe': 'Near Me',
    'filter.region': 'Region',
    'filter.regularFeeder': 'Regular Feeders',
    'filter.historical': 'Historical',
    'sort.nearest': 'Nearest',
    'sort.latest': 'Latest',
    'langar.verified': 'Verified',
    'langar.unverified': 'Unverified',
    'langar.regularFeeder': 'Verified Regular Feeder',
    'langar.historical': 'Historical Gurudwara',
    'langar.pending': 'Pending Verification',
    'langar.openForAll': 'Open for everyone',
    'langar.recurring': 'Recurring',
    'langar.daily': 'Daily',
    'langar.weekly': 'Weekly',
    'langar.directions': 'Get Directions',
    'langar.call': 'Call',
    'langar.save': 'Save',
    'langar.saved': 'Saved',
    'langar.share': 'Share',
    'langar.report': 'Report Listing',
    'langar.foodItems': 'Food Items',
    'langar.timing': 'Timing',
    'langar.contact': 'Contact',
    'langar.distance': 'Distance',
    'langar.viewDetails': 'View Details',
    'langar.qrCode': 'Download QR Code',
    'langar.views': 'Views',
    'langar.saves': 'Saves',
    'langar.directionsRequested': 'Directions Requested',
    'add.title': 'Add a Langar',
    'add.subtitle': 'Share a free community meal location with the community',
    'add.name': 'Gurudwara / Organizer Name',
    'add.location': 'Location',
    'add.date': 'Date',
    'add.time': 'Time',
    'add.contact': 'Contact Number',
    'add.details': 'Langar Details',
    'add.photo': 'Photo',
    'add.recurring': 'Recurring',
    'add.specialOccasion': 'Special Occasion',
    'add.submit': 'Submit Langar',
    'add.success': 'Langar submitted! It will be visible after admin verification.',
    'dashboard.myLangars': 'My Langars',
    'dashboard.savedLangars': 'Saved Langars',
    'dashboard.notifications': 'Notifications',
    'dashboard.settings': 'Settings',
    'dashboard.help': 'Help & Support',
    'dashboard.about': 'About',
    'dashboard.analytics': 'Analytics',
    'admin.title': 'Admin Dashboard',
    'admin.pending': 'Pending Verifications',
    'admin.reports': 'Reports',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.verify': 'Verify',
    'common.loading': 'Loading...',
    'common.noResults': 'No langars found',
    'common.search': 'Search',
    'common.map': 'Map',
    'common.list': 'List',
    'common.searchArea': 'Search this area',
  },
  pa: {
    'nav.home': 'ਘਰ',
    'nav.map': 'ਨਕਸ਼ਾ',
    'nav.add': 'ਲੰਗਰ ਜੋੜੋ',
    'nav.search': 'ਖੋਜ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.signin': 'ਸਾਈਨ ਇਨ',
    'nav.signout': 'ਸਾਈਨ ਆਉਟ',
    'hero.tagline': 'ਲੰਗਰ ਸਭ ਦਾ, ਸੇਵਾ ਸਭ ਲਈ',
    'hero.subtitle': 'ਆਪਣੇ ਨੇੜੇ ਗੁਰਦਵਾਰਿਆਂ ਅਤੇ ਥਾਵਾਂ ਤੇ ਮੁਫਤ ਕਮਿਊਨਿਟੀ ਭੋਜਨ ਲੱਭੋ',
    'hero.searchPlaceholder': 'ਆਪਣੇ ਨੇੜੇ ਲੰਗਰ ਖੋਜੋ',
    'hero.detectLocation': 'ਮੇਰਾ ਟਿਕਾਣਾ ਵਰਤੋ',
    'filter.nearby': 'ਨੇੜੇ',
    'filter.today': 'ਅੱਜ',
    'filter.tomorrow': 'ਕੱਲ੍ਹ',
    'filter.thisWeek': 'ਇਸ ਹਫ਼ਤੇ',
    'filter.all': 'ਸਭ',
    'filter.gurudwara': 'ਗੁਰਦਵਾਰਾ',
    'filter.community': 'ਕਮਿਊਨਿਟੀ',
    'filter.specialOccasion': 'ਖਾਸ ਮੌਕਾ',
    'filter.freeFood': 'ਮੁਫਤ ਭੋਜਨ',
    'filter.verified': 'ਸਿਰਫ ਪ੍ਰਮਾਣਿਤ',
    'filter.nearMe': 'ਮੇਰੇ ਨੇੜੇ',
    'sort.nearest': 'ਸਭ ਤੋਂ ਨੇੜੇ',
    'sort.latest': 'ਤਾਜ਼ਾ',
    'langar.verified': 'ਪ੍ਰਮਾਣਿਤ',
    'langar.pending': 'ਪ੍ਰਮਾਣਿਕਾ ਦੀ ਉਡੀਕ',
    'langar.openForAll': 'ਸਭ ਲਈ ਖੁੱਲ੍ਹਾ',
    'langar.recurring': 'ਮੁੜ ਮੁੜ',
    'langar.daily': 'ਰੋਜ਼ਾਨਾ',
    'langar.weekly': 'ਹਫ਼ਤਾਵਾਰ',
    'langar.directions': 'ਰਾਹ ਲਵੋ',
    'langar.call': 'ਕਾਲ ਕਰੋ',
    'langar.save': 'ਸੰਭਾਲੋ',
    'langar.saved': 'ਸੰਭਾਲਿਆ',
    'langar.share': 'ਸਾਂਝਾ ਕਰੋ',
    'langar.report': 'ਰਿਪੋਰਟ ਕਰੋ',
    'langar.foodItems': 'ਭੋਜਨ ਚੀਜ਼ਾਂ',
    'langar.timing': 'ਸਮਾਂ',
    'langar.contact': 'ਸੰਪਰਕ',
    'langar.distance': 'ਦੂਰੀ',
    'langar.viewDetails': 'ਵੇਰਵਾ ਵੇਖੋ',
    'langar.qrCode': 'QR ਕੋਡ ਡਾਊਨਲੋਡ ਕਰੋ',
    'langar.views': 'ਵਿਊਜ਼',
    'langar.saves': 'ਸੰਭਾਲੇ',
    'langar.directionsRequested': 'ਰਾਹ ਮੰਗੇ',
    'add.title': 'ਲੰਗਰ ਜੋੜੋ',
    'add.subtitle': 'ਕਮਿਊਨਿਟੀ ਨਾਲ ਮੁਫਤ ਭੋਜਨ ਟਿਕਾਣਾ ਸਾਂਝਾ ਕਰੋ',
    'add.name': 'ਗੁਰਦਵਾਰਾ / ਸੰਗਠਕ ਨਾਮ',
    'add.location': 'ਟਿਕਾਣਾ',
    'add.date': 'ਮਿਤੀ',
    'add.time': 'ਸਮਾਂ',
    'add.contact': 'ਸੰਪਰਕ ਨੰਬਰ',
    'add.details': 'ਲੰਗਰ ਵੇਰਵਾ',
    'add.photo': 'ਫੋਟੋ',
    'add.recurring': 'ਮੁੜ ਮੁੜ',
    'add.specialOccasion': 'ਖਾਸ ਮੌਕਾ',
    'add.submit': 'ਲੰਗਰ ਭੇਜੋ',
    'add.success': 'ਲੰਗਰ ਭੇਜਿਆ ਗਿਆ! ਇਹ ਹੁਣ ਸਾਰਿਆਂ ਨੂੰ ਦਿਖਾਈ ਦੇਵੇਗਾ।',
    'dashboard.myLangars': 'ਮੇਰੇ ਲੰਗਰ',
    'dashboard.savedLangars': 'ਸੰਭਾਲੇ ਲੰਗਰ',
    'dashboard.notifications': 'ਸੂਚਨਾਵਾਂ',
    'dashboard.settings': 'ਸੈਟਿੰਗਾਂ',
    'dashboard.help': 'ਮਦਦ ਅਤੇ ਸਹਿਯੋਗ',
    'dashboard.about': 'ਬਾਰੇ',
    'dashboard.analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'admin.title': 'ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ',
    'admin.pending': 'ਪ੍ਰਮਾਣਿਕਾ ਦੀ ਉਡੀਕ',
    'admin.reports': 'ਰਿਪੋਰਟਾਂ',
    'admin.approve': 'ਮਨਜ਼ੂਰ',
    'admin.reject': 'ਨਾਮਨਜ਼ੂਰ',
    'admin.verify': 'ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.noResults': 'ਕੋਈ ਲੰਗਰ ਨਹੀਂ ਮਿਲੇ',
    'common.search': 'ਖੋਜ',
    'common.map': 'ਨਕਸ਼ਾ',
    'common.list': 'ਸੂਚੀ',
    'common.searchArea': 'ਇਹ ਖੇਤਰ ਖੋਜੋ',
  },
  hi: {
    'nav.home': 'होम',
    'nav.map': 'नक्शा',
    'nav.add': 'लंगर जोड़ें',
    'nav.search': 'खोज',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.signin': 'साइन इन',
    'nav.signout': 'साइन आउट',
    'hero.tagline': 'लंगर सब का, सेवा सब लई',
    'hero.subtitle': 'अपने पास गुरुद्वारों और स्थानों पर मुफ्त सामुदायिक भोजन खोजें',
    'hero.searchPlaceholder': 'अपने पास लंगर खोजें',
    'hero.detectLocation': 'मेरा स्थान उपयोग करें',
    'filter.nearby': 'पास में',
    'filter.today': 'आज',
    'filter.tomorrow': 'कल',
    'filter.thisWeek': 'इस सप्ताह',
    'filter.all': 'सभी',
    'filter.gurudwara': 'गुरुद्वारा',
    'filter.community': 'समुदाय',
    'filter.specialOccasion': 'विशेष अवसर',
    'filter.freeFood': 'मुफ्त भोजन',
    'filter.verified': 'केवल सत्यापित',
    'filter.nearMe': 'मेरे पास',
    'sort.nearest': 'निकटतम',
    'sort.latest': 'नवीनतम',
    'langar.verified': 'सत्यापित',
    'langar.pending': 'सत्यापन लंबित',
    'langar.openForAll': 'सभी के लिए खुला',
    'langar.recurring': 'आवर्ती',
    'langar.daily': 'दैनिक',
    'langar.weekly': 'साप्ताहिक',
    'langar.directions': 'दिशा लें',
    'langar.call': 'कॉल करें',
    'langar.save': 'सहेजें',
    'langar.saved': 'सहेजा गया',
    'langar.share': 'साझा करें',
    'langar.report': 'रिपोर्ट करें',
    'langar.foodItems': 'भोजन वस्तुएं',
    'langar.timing': 'समय',
    'langar.contact': 'संपर्क',
    'langar.distance': 'दूरी',
    'langar.viewDetails': 'विवरण देखें',
    'langar.qrCode': 'QR कोड डाउनलोड करें',
    'langar.views': 'दृश्य',
    'langar.saves': 'सहेजे',
    'langar.directionsRequested': 'दिशा अनुरोधित',
    'add.title': 'लंगर जोड़ें',
    'add.subtitle': 'समुदाय के साथ मुफ्त भोजन स्थान साझा करें',
    'add.name': 'गुरुद्वारा / आयोजक नाम',
    'add.location': 'स्थान',
    'add.date': 'तारीख',
    'add.time': 'समय',
    'add.contact': 'संपर्क नंबर',
    'add.details': 'लंगर विवरण',
    'add.photo': 'फोटो',
    'add.recurring': 'आवर्ती',
    'add.specialOccasion': 'विशेष अवसर',
    'add.submit': 'लंगर जमा करें',
    'add.success': 'लंगर भेजा गया! यह अब सभी को दिखाई देगा।',
    'dashboard.myLangars': 'मेरे लंगर',
    'dashboard.savedLangars': 'सहेजे लंगर',
    'dashboard.notifications': 'सूचनाएं',
    'dashboard.settings': 'सेटिंग्स',
    'dashboard.help': 'सहायता और समर्थन',
    'dashboard.about': 'बारे में',
    'dashboard.analytics': 'विश्लेषण',
    'admin.title': 'एडमिन डैशबोर्ड',
    'admin.pending': 'सत्यापन लंबित',
    'admin.reports': 'रिपोर्ट्स',
    'admin.approve': 'स्वीकृत',
    'admin.reject': 'अस्वीकृत',
    'admin.verify': 'सत्यापित करें',
    'common.loading': 'लोड हो रहा है...',
    'common.noResults': 'कोई लंगर नहीं मिले',
    'common.search': 'खोज',
    'common.map': 'नक्शा',
    'common.list': 'सूची',
    'common.searchArea': 'इस क्षेत्र को खोजें',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('langar-lang') as Language | null;
    if (stored && ['en', 'pa', 'hi'].includes(stored)) {
      setLangState(stored);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('langar-lang', newLang);
  };

  const t = (key: string) => translations[lang][key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
